# Generated by Django 5.2.6 on 2025-11-03 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_LOGIN", "User login"),
                            ("USER_LOGOUT", "User logout"),
                            ("DASHBOARD_VIEWED", "Dashboard viewed"),
                            ("FEATURE_USED", "Feature used"),
                            ("OCR_UPLOADED", "OCR file uploaded"),
                            ("OCR_PROCESSED", "OCR processed"),
                            ("ANNOTATION_CREATED", "Annotation created"),
                            ("ANNOTATION_UPDATED", "Annotation updated"),
                            ("DATASET_SAVED", "Dataset saved"),
                            ("DATASET_VIEWED", "Dataset viewed"),
                            ("DATASET_DOWNLOADED", "Dataset downloaded"),
                        ],
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("target_app", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="audittrail__event_t_4256ce_idx",
                    ),
                    models.Index(
                        fields=["target_app", "target_model", "target_id"],
                        name="audittrail__target__e013d3_idx",
                    ),
                ],
            },
        ),
    ]
