"""
Django settings for kalbe_be project.

Generated by 'django-admin startproject' using Django 5.0.7.
Docs:
- https://docs.djangoproject.com/en/5.0/topics/settings/
- https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import os
import dj_database_url
from decouple import config
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")
STATICFILES_DIRS = [
    BASE_DIR / "static",        
]


# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config("SECRET_KEY_DJANGO")
SECRET_KEY = os.getenv("SECRET_KEY_DJANGO")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY_DJANGO is not set in environment")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"


ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://backend-mirror-production.up.railway.app",
]

CORS_ALLOW_METHODS = [  
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [ 
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

  
# Application definition

INSTALLED_APPS = [
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",
    "corsheaders",
    'authentication',
    'ocr',
    'csv_export',
    "annotation",
    "dataset",
    "django_filters",
    "rest_framework",
    "save_to_database",
    "dashboard",
    "chat", 
    "predictions",
    "user_settings",
]
# Email — DEV only: email dikirim ke console/locmem (test)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "noreply@kalbe.local"

# Password validators — enforce min length
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 8}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Security basics (dev values; prod => True + HTTPS)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

TIME_ZONE = "Asia/Jakarta"
USE_TZ = True

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = "kalbe_be.urls"


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    # keep your pagination if you had it:
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}



TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kalbe_be.wsgi.application"

DATABASE_URL = config("DATABASE_URL", default=None)

if DATABASE_URL:
    DATABASES = {
        "default": {
            **dj_database_url.parse(DATABASE_URL, conn_max_age=600),
            'ENGINE': 'django_prometheus.db.backends.postgresql',  
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }


LANGUAGE_CODE = "en-us"
USE_I18N = True


STATIC_URL = "/static/"
# Dev: For static files
STATICFILES_DIRS = [BASE_DIR / "static"]  
# Prod: where collectstatic gathers all files
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ----------------------------------------------------
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)

EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")  # <-- default kosong
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# Kalau kredensial gak ada (CI), pakai console backend biar gak error
if not EMAIL_HOST_USER:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# kalau DEFAULT_FROM_EMAIL gak ada di .env, pakai EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_TIMEOUT = 10

GEMINI_API_KEY = config("GEMINI_API_KEY", default=None)
GEMINI_MODEL   = config("GEMINI_MODEL", default="gemini-2.5-flash")
GEMINI_TEMP    = config("GEMINI_TEMP", cast=float, default=0.4)
USE_GEMINI     = config("USE_GEMINI", cast=bool, default=True)

ML_RUNNER_PY = os.getenv(
    "ML_RUNNER_PY",
    str(BASE_DIR / "predictions" / "run_model.py")
)