# Generated by Django 5.2.6 on 2025-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ocr.completed', 'Pemrosesan OCR Selesai'), ('ocr.failed', 'Pemrosesan OCR Gagal'), ('chat.reply', 'Respons Chat Baru'), ('system', 'Notifikasi Sistem')], max_length=50),
        ),
    ]
