# Generated by Django 5.2.6 on 2025-10-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/csvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_json', models.JSONField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
