# Generated by Django 5.2.6 on 2025-10-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_to_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='uploaded_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
