# Generated by Django 5.2.6 on 2025-11-29 16:09

import save_to_database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save_to_database', '0002_csv_uploaded_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file',
            field=save_to_database.models.VirtualFileField(blank=True, default='', max_length=500),
        ),
    ]
