# Generated by Django 5.2.6 on 2025-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_comment_annotation_label_document_content_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
