# Generated by Django 5.2.6 on 2025-09-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_alter_annotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
