# Generated by Django 5.2.6 on 2025-10-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_otp_code_user_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
    ]
