# Generated by Django 5.2.6 on 2025-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_account_locked_until_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
