# Generated by Django 5.2.7 on 2025-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
