# Generated by Django 5.2.6 on 2025-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_initials', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('smoking_habit', models.CharField(max_length=20)),
                ('smoker', models.IntegerField()),
                ('drinking_habit', models.CharField(max_length=20)),
                ('hemoglobin', models.DecimalField(decimal_places=2, max_digits=4)),
                ('random_blood_glucose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sgpt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alkaline_phosphatase', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
