# Generated by Django 5.2.6 on 2025-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_alter_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ocr', 'OCR Processing'), ('annotation', 'Document Annotation'), ('file_move', 'File Movement'), ('comment', 'Comment Added'), ('file_upload', 'File Upload'), ('folder_move', 'Folder Move')], max_length=20),
        ),
    ]
